### ISSUE TITLE
Issues I have noticed while playing with mates on Poseidon's server (as of 18/7/15)

### ISSUE THREAD

**Issue by Splerge** [Alig96/nzombies#61]
-If you double tap the use key on doors or the power switch, sometimes it closes/returns to off and stays there. I've noticed you have a delay built in to stop this already, so I suggest you multiply this delay by 1.5-2.5.
-If a player disconnects mid round it breaks the game, requiring a server reset, as zombies won't spawn. Lebofly found a fix which just reduces the player count every time someone leaves the server, and has submitted it as a pull request.

- in COD: Zombies repairing a barricade gives you 10 points. Should be a simple copy and paste job from the script that gives you money when you shoot zambs

- in create mode, or while using /load, the selection boxes that pop up can be seen by everyone on the server simultaneously. Now, I know that create mode is only really meant for one person, but it's probably worth fixing regardless.

-You've probably already fixed this but Juggernog only costs 100, not 2500

-One of the tabs in the props menu is called "dicks" lolwat

**Comment by Alig96** [comment]
- I have tried to replicate this bug but can't, so if you can tell me the exact steps to replicate it that would be great!
- Fixed
- Added
- Fixed, thanks for this pretty big bug.
- Used for testing purposes, ask the server admin to change the settings.
- Eh, removed.
