### ISSUE TITLE
Not an actual issue, looking to possible set up a server...

### ISSUE THREAD

**Issue by minin43** [Alig96/nzombies#63]
I used to be really interested in this gamemode awhile back (had a server going for a little bit), but lost interest when it stop getting (I guess only temporarily) updated. I've now been getting emails about updates, and I've come back with renewed interest. I have some questions for the dev if you'd friend me on Steam http://steamcommunity.com/profiles/76561198029935530/

P.S. sorry I don't really know how to work github, this is the closest thing I can get to a message.

**Comment by Alig96** [comment]
Added.
