### ISSUE TITLE
Players can have more than x weapons

### ISSUE THREAD

**Issue by epicskymi** [Alig96/nzombies#64]
Is this implemented haven't used v3 yet but before In v2 I had 8x weapons with max ammo was ridiculous :3

**Comment by Splerge** [comment]
I don't think it's implemented in v3 either. Trying to find a fix myself

**Comment by Alig96** [comment]
No I haven't implemented it as of yet but it should be simple to add.

**Comment by Splerge** [comment]
this is what the Poseidon server is using.
At the bottom of sh_player_ingame.lua:
function nz.Players.Functions.canCarryWeapon(pl, weapon)
	local limit = 2 //change this value if you want to be able to hold more weapons!
	if #pl:GetWeapons() >= limit then
				pl:StripWeapon(pl:GetActiveWeapon():GetClass())
				timer.Simple(0.1, function() pl:SelectWeapon(weapon:GetClass()) end)
				return true
	end
	return false
end

and after the players spawn in the round, you want to add the hook:
gamemode/round_handler/sv_handler.lua
line 82:
timer.Simple( 0.1, function() hook.Add("PlayerCanPickupWeapon", "ManualWeaponPickup_CanPickup", function(pl, ent)					
								nz.Players.Functions.canCarryWeapon(pl, ent)
								end) end)

and remove the hook when the game is reset:
line 123, still in sv_handler.lua:
hook.Remove("PlayerCanPickupWeapon", "ManualWeaponPickup_CanPickup")

**Comment by Alig96** [comment]
I've got a simpler way of implementing it, in my local version in the OnSpawned hook (that I've got somewhere) which does similar logic in there instead. Just easier and less code. I haven't had time to make the latest push with this change and easter egg tool unfortunately :(

**Comment by Alig96** [comment]
Implemented: https://github.com/Alig96/nzombies/commit/017148348aa59330e13fc34b29e8abfd582f632d
